;(global-unset-key (kbd "C-h t"))
;(global-unset-key (kbd "M-."))
;(global-set-key (kbd "C-i") 'previous-line)
;(global-set-key (kbd "C-k") 'next-line)
;(global-set-key (kbd "C-j") 'backward-char)
;(global-set-key (kbd "C-l") 'forward-char)
;(global-set-key (kbd "C-;") 'recenter-top-bottom)
;(global-set-key (kbd "C-f") 'scroll-up-command)
;(global-set-key (kbd "C-b") 'scroll-down-command)
;(global-set-key (kbd "C-p") 'isearch-backward)
;(global-set-key (kbd "C-n") 'isearch-forward)
;(global-set-key (kbd "C-w") 'kill-ring-save)
;(global-set-key (kbd "M-w") 'kill-region)
;(global-set-key (kbd "C-v") 'yank)
;(global-set-key (kbd "M-v") 'yank-pop)
;(global-set-key (kbd "C-<backspace>") 'kill-whole-line)
;(global-set-key (kbd "M-<delete>") 'kill-whole-line)
;(global-set-key (kbd "C-<delete>") 'kill-line)
(global-set-key (kbd "M-o") 'other-window)
;(global-set-key (kbd "M-i") 'backward-list)
;(global-set-key (kbd "M-k") 'forward-list)
;(global-set-key (kbd "M-j") 'backward-word)
;(global-set-key (kbd "M-l") 'forward-word)
(global-set-key (kbd "M-,") 'previous-buffer)
(global-set-key (kbd "M-.") 'next-buffer)

(setq package-archives
      '(("gnu"   . "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
       ("melpa" . "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")))
(require 'package)
(package-initialize)
;(desktop-save-mode 1)

(set-background-color "black")
(set-foreground-color "white")
(setq inhibit-startup-screen t)
(setq initial-buffer-choice (quote shell))
(global-display-line-numbers-mode 1)
(setq line-number-display-limit nil)
(scroll-bar-mode 0)
(tool-bar-mode 0)
(setq display-time-24hr-format t)
(display-time-mode 1)
(setq-default cursor-type 'bar) 
(setq blink-cursor-blinks 0)
(column-number-mode 1)
(display-battery-mode)
(setq default-input-method 'rime)
(setq confirm-kill-processes nil)
(setq use-dialog-box nil)
;(tooltip-mode 1)

(global-company-mode)
(setq company-idle-delay 0.01)

(custom-set-faces
 '(default ((t (:family "Noto Sans Mono" :foundry "GOOG" :slant normal
			:weight normal :height 97 :width normal)))))
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)
(setq echo-keystrokes 0.01)
(icomplete-mode t)
(windmove-default-keybindings)
(winner-mode 1)
(add-hook 'emacs-lisp-mode-hook 'show-paren-mode)
(setq read-quoted-char-radix 10) 
(setq resize-mini-windows t)
;(setq enable-recursive-minibuffers t)
(setq completion-cycle-threshold 5)
(setq suggest-key-bindings 9)
(setq help-at-pt-display-when-idle t)
(put 'set-goal-column 'disabled nil)
(setq apropos-do-all 1)
(setq register-preview-delay 0.001)
(setq bookmark-save-flag 1)
(setq scroll-preserve-screen-position t)
(setq scroll-conservatively 999)
(setq auth-sources '("~/.authinfo.gpg" "~/.authinfo" "~/.netrc"))

(setq erc-nick "om1111on"
      erc-user-full-name "om1111on"
      erc-prompt-for-password 1)
;(setq erc-autojoin-channels-alist "#emacs")
(setq erc-ignore-list nil)
(setq erc-hide-list
      '("JOIN" "PART" "QUIT" ))

(setq user-full-name "om1111on")
(setq user-mail-address "om1111on@163.com")
(load-library "smtpmail")
(require 'smtpmail)
(setq message-send-mail-function 'smtpmail-send-it)
(setq send-mail-function 'smtpmail-send-it)
(setq smtpmail-local-domain "R")
(setq smtpmail-smtp-server "smtp.163.com")
(setq smtpmail-smtp-user "om1111on")
(setq smtpmail-smtp-service 465 )
(setq smtpmail-stream-type 'ssl)
(setq rmail-file-name "~/.emacs.d/RMAIL")
(setq rmail-movemail-program "/usr/bin/movemail.mailutils")
(setenv "MAILHOST" "pop.163.com")
(setq rmail-primary-inbox-list '("po:om1111on")
      rmail-pop-password-required t)
(setq rmail-remote-password "")
